In [40]:
import pandas as pd 
import numpy
from sklearn.preprocessing import MinMaxScaler
import datetime
import random
pd.set_option('display.max_columns', 500)

In [43]:
data = pd.read_csv('../../Wadi_data/attacks_october_clean_with_label.csv', index_col = ['DATETIME'], parse_dates=True)
df_train_orig = pd.read_csv("../../Wadi_data/14_days_clean.csv",  parse_dates = {'DATETIME': ['Date','Time']} , dayfirst=True)

In [ ]:
#data = data.drop(columns=['Unnamed: 0'], axis=1)

In [44]:
attacks = data.loc[data['ATT_FLAG'] == 1] #find attacks among data
prev_datetime = attacks.index[0] #find first timing

start = prev_datetime 
count_attacks = 0
#find attacks bpunds
attacks_intervals = pd.DataFrame(columns = ['Name', 'Start', 'End', 'Replay_Copy'])
for index, row in attacks.iterrows():
    if (index - prev_datetime >  datetime.timedelta(seconds=10)): #change attack
        count_attacks = count_attacks + 1
        interval = pd.DataFrame([['attack_'+str(count_attacks), start, prev_datetime, (start - (prev_datetime - start)) - datetime.timedelta(days = random.randint(2,13))]], columns = ['Name', 'Start', 'End', 'Replay_Copy'])
        attacks_intervals = attacks_intervals.append(interval)
        start = index
    prev_datetime = index
count_attacks = count_attacks + 1
interval = pd.DataFrame([['attack_'+str(count_attacks), start, prev_datetime, start - (prev_datetime - start) - datetime.timedelta(days = random.randint(2,13))]], columns = ['Name', 'Start', 'End', 'Replay_Copy'])
attacks_intervals = attacks_intervals.append(interval)
attacks_intervals.set_index(['Name'])

                        Start                 End         Replay_Copy
Name
attack_1  2017-10-09 19:25:00 2017-10-09 19:50:16 2017-09-30 18:59:44
attack_2  2017-10-10 10:24:10 2017-10-10 10:34:00 2017-09-30 10:14:20
attack_3  2017-10-10 10:55:00 2017-10-10 11:24:00 2017-10-02 10:26:00
attack_4  2017-10-10 11:30:40 2017-10-10 11:44:50 2017-10-04 11:16:30
attack_5  2017-10-10 13:39:30 2017-10-10 13:50:40 2017-10-01 13:28:20
attack_6  2017-10-10 14:48:17 2017-10-10 15:00:32 2017-10-07 14:36:02
attack_7  2017-10-10 17:40:00 2017-10-10 17:49:40 2017-10-02 17:30:20
attack_8  2017-10-11 10:55:00 2017-10-11 10:56:27 2017-09-28 10:53:33
attack_9  2017-10-11 11:17:54 2017-10-11 11:31:20 2017-10-05 11:04:28
attack_10 2017-10-11 11:36:31 2017-10-11 11:47:00 2017-10-03 11:26:02
attack_11 2017-10-11 11:59:00 2017-10-11 12:05:00 2017-10-03 11:53:00
attack_12 2017-10-11 12:07:30 2017-10-11 12:10:52 2017-10-04 12:04:08
attack_13 2017-10-11 12:16:00 2017-10-11 12:25:36 2017-10-07 12:06:24
attack_14 2017-10-11 15:26:30 2017-10-11 15:37:00 2017-09-30 15:16:00

In [52]:
count = 0
prev_end = data.index[0]
df2 = pd.DataFrame()
#replay data
for index, row in attacks_intervals.iterrows():
    #fill with data between an atack an the other
    df2 = df2.append(data.loc[prev_end : row['Start']])
    df = pd.DataFrame()
    df.append(data.loc[row['Replay_Copy'] : row['Start']-datetime.timedelta(days=(row['Start']-(row['Replay_Copy'])).days)])#append replayed row 
    df.index = data.index[row['Start']: row['End']]#update datetime
    df.ATT_FLAG = 1 #update attack flag
    print(df)
    df2 = df2.append(df, ignore_index = True)
    prev_end = row['End']
for i in numpy.arange(prev_end, data['DATETIME'].tail(1).item(), 0.25):
        df2 = df2.append(data.loc[data['DATETIME'] == i])

TypeError: unsupported type for timedelta days component: Timedelta

In [6]:
df2.loc[df2['DATETIME'] == 2009.50] - data.loc[data['DATETIME'] == 2009.50]

,DATETIME,PRESSURE_T1,PRESSURE_T2,PRESSURE_T3,PRESSURE_T4,PRESSURE_T5,PRESSURE_T6,PRESSURE_T7,PRESSURE_J280,PRESSURE_J269,PRESSURE_J300,PRESSURE_J256,PRESSURE_J289,PRESSURE_J415,PRESSURE_J302,PRESSURE_J306,PRESSURE_J307,PRESSURE_J317,PRESSURE_J14,PRESSURE_J422,FLOW_PU1,FLOW_PU2,FLOW_PU3,FLOW_PU4,FLOW_PU5,FLOW_PU6,FLOW_PU7,FLOW_PU8,FLOW_PU9,FLOW_PU10,FLOW_PU11,FLOW_V2,STATUS_PU1,STATUS_PU2,STATUS_PU3,STATUS_PU4,STATUS_PU5,STATUS_PU6,STATUS_PU7,STATUS_PU8,STATUS_PU9,STATUS_PU10,STATUS_PU11,STATUS_V2,ATT_FLAG
8038,0.0,-1.8476,4.5692,-0.4972,-0.9516,0.0,-0.0449,1.6539,-0.0145,13.2249,6.0319,5.3796,6.0712,-20.6671,8.7709,18.2576,8.9264,-10.7745,5.7303,5.7303,-23.6901,96.7265,0.0,0.0,0.0,0.0,-49.2182,-8.3265,0.0,6.6588,-24.9029,-25.2951,0.0,1.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,-1.0,0.0,0.0

In [7]:
df2.to_csv('data/replay_attacks/dataset_1_replay.csv')